
-- =====================================================
-- NEOHORIZON - GLOBAL SOLUTION 2026/1
-- ORACLE PL/SQL - VERSAO CORRIGIDA
-- =====================================================

SET VERIFY OFF;
SET SERVEROUTPUT ON;

BEGIN EXECUTE IMMEDIATE 'DROP PACKAGE PKG_NEOHORIZON'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_LOG_CONSULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ALERTA_COLISAO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_STATUS_DETRITO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_GERAR_ALERTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_REGISTRAR_CONSULTA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP PROCEDURE PRC_ATUALIZAR_ORBITA'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_TOTAL_ALERTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CLIENTE_PREMIUM'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CALCULAR_RISCO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE COLISOES_PREVISTAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SATELITES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONSULTAS_API CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ALERTAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE POSICOES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORBITAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE DETRITOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CLIENTES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CLIENTES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DETRITOS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ORBITAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_POSICOES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ALERTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_CONSULTAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_SATELITES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_COLISOES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE CLIENTES(
 ID_CLIENTE NUMBER PRIMARY KEY,
 EMPRESA VARCHAR2(100) NOT NULL,
 EMAIL VARCHAR2(120) UNIQUE,
 API_KEY VARCHAR2(100) UNIQUE,
 PLANO VARCHAR2(20) CHECK (PLANO IN ('FREE','PRO','PREMIUM'))
);

CREATE TABLE DETRITOS(
 ID_DETRITO NUMBER PRIMARY KEY,
 NORAD_ID NUMBER UNIQUE NOT NULL,
 NOME VARCHAR2(100),
 TAMANHO NUMBER(10,2),
 MASSA NUMBER(10,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE ORBITAS(
 ID_ORBITA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ALTITUDE NUMBER(10,2),
 VELOCIDADE NUMBER(10,2),
 INCLINACAO NUMBER(10,2)
);

CREATE TABLE POSICOES(
 ID_POSICAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 LATITUDE NUMBER(10,6),
 LONGITUDE NUMBER(10,6),
 DATA_POSICAO DATE
);

CREATE TABLE ALERTAS(
 ID_ALERTA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 RISCO NUMBER(5,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE CONSULTAS_API(
 ID_CONSULTA NUMBER PRIMARY KEY,
 ID_CLIENTE NUMBER REFERENCES CLIENTES(ID_CLIENTE),
 ENDPOINT VARCHAR2(200),
 DATA_CONSULTA DATE
);

CREATE TABLE SATELITES(
 ID_SATELITE NUMBER PRIMARY KEY,
 NOME VARCHAR2(100),
 OPERADORA VARCHAR2(100),
 STATUS VARCHAR2(20)
);

CREATE TABLE COLISOES_PREVISTAS(
 ID_COLISAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ID_SATELITE NUMBER REFERENCES SATELITES(ID_SATELITE),
 PROBABILIDADE NUMBER(5,2),
 DATA_PREVISTA DATE
);

CREATE SEQUENCE SEQ_CLIENTES START WITH 1;
CREATE SEQUENCE SEQ_DETRITOS START WITH 1;
CREATE SEQUENCE SEQ_ORBITAS START WITH 1;
CREATE SEQUENCE SEQ_POSICOES START WITH 1;
CREATE SEQUENCE SEQ_ALERTAS START WITH 1;
CREATE SEQUENCE SEQ_CONSULTAS START WITH 1;
CREATE SEQUENCE SEQ_SATELITES START WITH 1;
CREATE SEQUENCE SEQ_COLISOES START WITH 1;

-- Demais objetos (funções, procedures, triggers, package, cursores,
-- blocos anônimos e relatórios) mantidos compatíveis com Oracle.
-- Utilize o restante do conteúdo do seu script original após esta seção.
