-- =====================================================
-- NEOHORIZON - GLOBAL SOLUTION 2026/1
-- ORACLE PL/SQL COMPLETE ACADEMIC SCRIPT
-- =====================================================

-- =====================================================
-- 1. APAGAR ESTRUTURAS (OPCIONAL - PARA REEXECUÇÃO)
-- =====================================================
DROP PACKAGE PKG_NEOHORIZON;
DROP TRIGGER TRG_LOG_CONSULTA;
DROP TRIGGER TRG_ALERTA_COLISAO;
DROP TRIGGER TRG_STATUS_DETRITO;
DROP PROCEDURE PRC_GERAR_ALERTA;
DROP PROCEDURE PRC_REGISTRAR_CONSULTA;
DROP PROCEDURE PRC_ATUALIZAR_ORBITA;
DROP FUNCTION FN_TOTAL_ALERTAS;
DROP FUNCTION FN_CLIENTE_PREMIUM;
DROP FUNCTION FN_CALCULAR_RISCO;
DROP TABLE COLISOES_PREVISTAS CASCADE CONSTRAINTS;
DROP TABLE SATELITES CASCADE CONSTRAINTS;
DROP TABLE CONSULTAS_API CASCADE CONSTRAINTS;
DROP TABLE ALERTAS CASCADE CONSTRAINTS;
DROP TABLE POSICOES CASCADE CONSTRAINTS;
DROP TABLE ORBITAS CASCADE CONSTRAINTS;
DROP TABLE DETRITOS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP SEQUENCE SEQ_CLIENTES;
DROP SEQUENCE SEQ_DETRITOS;
DROP SEQUENCE SEQ_ORBITAS;
DROP SEQUENCE SEQ_POSICOES;
DROP SEQUENCE SEQ_ALERTAS;
DROP SEQUENCE SEQ_CONSULTAS;
DROP SEQUENCE SEQ_SATELITES;
DROP SEQUENCE SEQ_COLISOES;

-- =====================================================
-- 2. CRIAÇÃO DAS TABELAS (DDL)
-- =====================================================
CREATE TABLE CLIENTES(
 ID_CLIENTE NUMBER PRIMARY KEY,
 EMPRESA VARCHAR2(100) NOT NULL,
 EMAIL VARCHAR2(120) UNIQUE,
 API_KEY VARCHAR2(100) UNIQUE,
 PLANO VARCHAR2(20) CHECK (PLANO IN ('FREE','PRO','PREMIUM'))
);

CREATE TABLE DETRITOS(
 ID_DETRITO NUMBER PRIMARY KEY,
 NORAD_ID NUMBER UNIQUE NOT NULL,
 NOME VARCHAR2(100),
 TAMANHO NUMBER(10,2),
 MASSA NUMBER(10,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE ORBITAS(
 ID_ORBITA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ALTITUDE NUMBER(10,2),
 VELOCIDADE NUMBER(10,2),
 INCLINACAO NUMBER(10,2)
);

CREATE TABLE POSICOES(
 ID_POSICAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 LATITUDE NUMBER(10,6),
 LONGITUDE NUMBER(10,6),
 DATA_POSICAO DATE
);

CREATE TABLE ALERTAS(
 ID_ALERTA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 RISCO NUMBER(5,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE CONSULTAS_API(
 ID_CONSULTA NUMBER PRIMARY KEY,
 ID_CLIENTE NUMBER REFERENCES CLIENTES(ID_CLIENTE),
 ENDPOINT VARCHAR2(200),
 DATA_CONSULTA DATE
);

CREATE TABLE SATELITES(
 ID_SATELITE NUMBER PRIMARY KEY,
 NOME VARCHAR2(100),
 OPERADORA VARCHAR2(100),
 STATUS VARCHAR2(20)
);

CREATE TABLE COLISOES_PREVISTAS(
 ID_COLISAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ID_SATELITE NUMBER REFERENCES SATELITES(ID_SATELITE),
 PROBABILIDADE NUMBER(5,2),
 DATA_PREVISTA DATE
);

-- =====================================================
-- 3. CRIAÇÃO DAS SEQUENCES
-- =====================================================
CREATE SEQUENCE SEQ_CLIENTES START WITH 1;
CREATE SEQUENCE SEQ_DETRITOS START WITH 1;
CREATE SEQUENCE SEQ_ORBITAS START WITH 1;
CREATE SEQUENCE SEQ_POSICOES START WITH 1;
CREATE SEQUENCE SEQ_ALERTAS START WITH 1;
CREATE SEQUENCE SEQ_CONSULTAS START WITH 1;
CREATE SEQUENCE SEQ_SATELITES START WITH 1;
CREATE SEQUENCE SEQ_COLISOES START WITH 1;

-- =====================================================
-- 4. CARGA DE DADOS (DML - +80 REGISTROS CONVENIENTES)
-- =====================================================
SET SERVEROUTPUT ON;
BEGIN
 FOR I IN 1..10 LOOP
   INSERT INTO CLIENTES VALUES(SEQ_CLIENTES.NEXTVAL, 'EMPRESA '||I, 'EMAIL'||I||'@NEOHORIZON.COM', 'KEY_NEO_'||I,
   CASE WHEN MOD(I,3)=0 THEN 'PREMIUM' WHEN MOD(I,2)=0 THEN 'PRO' ELSE 'FREE' END);
 END LOOP;

 FOR I IN 1..30 LOOP
   INSERT INTO DETRITOS VALUES(SEQ_DETRITOS.NEXTVAL, 10000+I, 'DETRITO '||I, I * 1.5, I * 5, 'ATIVO');
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO ORBITAS VALUES(SEQ_ORBITAS.NEXTVAL, I, 500 + (I*10), 7.5 + (I/10), 98.0);
 END LOOP;

 FOR I IN 1..20 LOOP
   INSERT INTO POSICOES VALUES(SEQ_POSICOES.NEXTVAL, MOD(I,10)+1, -23.55 + (I/100), -46.63 + (I/100), SYSDATE-I);
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO ALERTAS VALUES(SEQ_ALERTAS.NEXTVAL, MOD(I,10)+1, 45.0 + I, 'ATIVO');
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO SATELITES VALUES(SEQ_SATELITES.NEXTVAL, 'SATELITE-'||I, 'NEO-CONSTELLATION', 'ATIVO');
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO COLISOES_PREVISTAS VALUES(SEQ_COLISOES.NEXTVAL, I, I, 15.0 + (I*7), SYSDATE + I);
 END LOOP;

 COMMIT;
END;
/

-- =====================================================
-- 5. FUNÇÕES (FUNCTIONS)
-- =====================================================
CREATE OR REPLACE FUNCTION FN_TOTAL_ALERTAS RETURN NUMBER IS
 V_TOTAL NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_TOTAL FROM ALERTAS;
 RETURN V_TOTAL;
END;
/

CREATE OR REPLACE FUNCTION FN_CLIENTE_PREMIUM(P_ID NUMBER) RETURN VARCHAR2 IS
 V_PLANO VARCHAR2(20);
BEGIN
 SELECT PLANO INTO V_PLANO FROM CLIENTES WHERE ID_CLIENTE = P_ID;
 IF V_PLANO = 'PREMIUM' THEN 
    RETURN 'SIM'; 
 ELSE 
    RETURN 'NAO'; 
 END IF;
EXCEPTION
 WHEN NO_DATA_FOUND THEN
    RETURN 'INEXISTENTE';
END;
/

CREATE OR REPLACE FUNCTION FN_CALCULAR_RISCO(P_PROB NUMBER) RETURN VARCHAR2 IS
BEGIN
 IF P_PROB < 30 THEN 
    RETURN 'BAIXO';
 ELSIF P_PROB < 70 THEN 
    RETURN 'MEDIO';
 ELSE 
    RETURN 'ALTO';
 END IF;
END;
/

-- =====================================================
-- 6. PROCEDIMENTOS (PROCEDURES)
-- =====================================================
CREATE OR REPLACE PROCEDURE PRC_GERAR_ALERTA(P_DETRITO NUMBER, P_RISCO NUMBER) IS
BEGIN
 INSERT INTO ALERTAS VALUES(SEQ_ALERTAS.NEXTVAL, P_DETRITO, P_RISCO, 'ATIVO');
END;
/

CREATE OR REPLACE PROCEDURE PRC_REGISTRAR_CONSULTA(P_CLIENTE NUMBER, P_ENDPOINT VARCHAR2) IS
BEGIN
 INSERT INTO CONSULTAS_API VALUES(SEQ_CONSULTAS.NEXTVAL, P_CLIENTE, P_ENDPOINT, SYSDATE);
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_ORBITA(P_ID NUMBER, P_ALT NUMBER) IS
BEGIN
 UPDATE ORBITAS SET ALTITUDE = P_ALT WHERE ID_DETRITO = P_ID;
END;
/

-- =====================================================
-- 7. GATILHOS (TRIGGERS)
-- =====================================================
CREATE OR REPLACE TRIGGER TRG_LOG_CONSULTA
AFTER INSERT ON CONSULTAS_API
FOR EACH ROW
BEGIN
 DBMS_OUTPUT.PUT_LINE('LOG NeoHorizon: Endpoint ' || :NEW.ENDPOINT || ' acessado.');
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTA_COLISAO
AFTER INSERT ON COLISOES_PREVISTAS
FOR EACH ROW
BEGIN
 IF :NEW.PROBABILIDADE > 70 THEN
   INSERT INTO ALERTAS VALUES(SEQ_ALERTAS.NEXTVAL, :NEW.ID_DETRITO, :NEW.PROBABILIDADE, 'CRITICO');
 END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STATUS_DETRITO
BEFORE UPDATE ON DETRITOS
FOR EACH ROW
BEGIN
 :NEW.STATUS := UPPER(:NEW.STATUS);
END;
/

-- =====================================================
-- 8. PACOTES (PACKAGES)
-- =====================================================
CREATE OR REPLACE PACKAGE PKG_NEOHORIZON AS
 FUNCTION TOTAL_ALERTAS RETURN NUMBER;
 PROCEDURE GERAR_ALERTA(P_DETRITO NUMBER, P_RISCO NUMBER);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_NEOHORIZON AS
 FUNCTION TOTAL_ALERTAS RETURN NUMBER IS
 BEGIN
  RETURN FN_TOTAL_ALERTAS;
 END;
 PROCEDURE GERAR_ALERTA(P_DETRITO NUMBER, P_RISCO NUMBER) IS
 BEGIN
  PRC_GERAR_ALERTA(P_DETRITO, P_RISCO);
 END;
END;
/

-- =====================================================
-- 9. CURSORES EXPLÍCITOS
-- =====================================================
DECLARE
 CURSOR C1 IS SELECT ID_DETRITO, NOME, TAMANHO FROM DETRITOS WHERE TAMANHO > 10;
 R_DET C1%ROWTYPE;
BEGIN
 OPEN C1;
 LOOP
   FETCH C1 INTO R_DET;
   EXIT WHEN C1%NOTFOUND;
   DBMS_OUTPUT.PUT_LINE('Cursor 1 - Detrito Grande: ' || R_DET.NOME || ' | Tam: ' || R_DET.TAMANHO);
 END LOOP;
 CLOSE C1;
END;
/

DECLARE
 CURSOR C2 IS SELECT EMPRESA, EMAIL FROM CLIENTES WHERE PLANO = 'PREMIUM';
 R_CLI C2%ROWTYPE;
BEGIN
 OPEN C2;
 LOOP
   FETCH C2 INTO R_CLI;
   EXIT WHEN C2%NOTFOUND;
   DBMS_OUTPUT.PUT_LINE('Cursor 2 - Cliente Premium: ' || R_CLI.EMPRESA || ' | ' || R_CLI.EMAIL);
 END LOOP;
 CLOSE C2;
END;
/

DECLARE
 CURSOR C3 IS SELECT ID_ALERTA, RISCO FROM ALERTAS WHERE STATUS = 'ATIVO';
 R_ALE C3%ROWTYPE;
BEGIN
 OPEN C3;
 LOOP
   FETCH C3 INTO R_ALE;
   EXIT WHEN C3%NOTFOUND;
   DBMS_OUTPUT.PUT_LINE('Cursor 3 - Alerta Ativo ID: ' || R_ALE.ID_ALERTA || ' | Risco: ' || R_ALE.RISCO || '%');
 END LOOP;
 CLOSE C3;
END;
/

DECLARE
 CURSOR C4 IS SELECT NOME, OPERADORA FROM SATELITES;
 R_SAT C4%ROWTYPE;
BEGIN
 OPEN C4;
 LOOP
   FETCH C4 INTO R_SAT;
   EXIT WHEN C4%NOTFOUND;
   DBMS_OUTPUT.PUT_LINE('Cursor 4 - Satélite: ' || R_SAT.NOME || ' | Operadora: ' || R_SAT.OPERADORA);
 END LOOP;
 CLOSE C4;
END;
/

-- =====================================================
-- 10. BLOCOS ANÔNIMOS
-- =====================================================

-- Bloco 1
DECLARE 
 V_QTD NUMBER;
BEGIN
 SELECT COUNT(*) INTO V_QTD FROM DETRITOS;
 IF V_QTD = 0 THEN
    RAISE NO_DATA_FOUND;
 END IF;
 DBMS_OUTPUT.PUT_LINE('Bloco 1 - Total de Detritos Cadastrados: ' || V_QTD);
EXCEPTION 
 WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 1 - Erro: Nenhum detrito encontrado.');
 WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 1 - Erro inesperado.');
END;
/

-- Bloco 2
DECLARE 
 V_STATUS VARCHAR2(20);
BEGIN
 SELECT STATUS INTO V_STATUS FROM DETRITOS WHERE ID_DETRITO = 999;
 DBMS_OUTPUT.PUT_LINE('Bloco 2 - Status: ' || V_STATUS);
EXCEPTION 
 WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 2 - Sucesso no Tratamento: Detrito 999 não existe.');
END;
/

-- Bloco 3
DECLARE 
 V_RISCO NUMBER := 85;
 V_GRAVIDADE VARCHAR2(30);
BEGIN
 IF V_RISCO < 30 THEN 
    V_GRAVIDADE := 'ESTÁVEL / BAIXO';
 ELSIF V_RISCO BETWEEN 30 AND 70 THEN 
    V_GRAVIDADE := 'ATENÇÃO / MÉDIO';
 ELSE 
    V_GRAVIDADE := 'CRÍTICO / ALTO';
 END IF;
 DBMS_OUTPUT.PUT_LINE('Bloco 3 - Nível de Risco Simulado: ' || V_GRAVIDADE);
 
 IF V_RISCO > 0 THEN
    V_RISCO := V_RISCO / 0;
 END IF;
EXCEPTION 
 WHEN ZERO_DIVIDE THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 3 - Exceção Tratada: Divisão por zero monitorada.');
END;
/

-- Bloco 4
DECLARE 
 V_CONTADOR NUMBER := 1;
 V_NOME_DET VARCHAR2(100);
BEGIN
 WHILE V_CONTADOR <= 5 LOOP
   SELECT NOME INTO V_NOME_DET FROM DETRITOS WHERE ID_DETRITO = V_CONTADOR;
   DBMS_OUTPUT.PUT_LINE('Bloco 4 (WHILE) - Detrito consultado: ' || V_NOME_DET);
   V_CONTADOR := V_CONTADOR + 1;
 END LOOP;
EXCEPTION 
 WHEN TOO_MANY_ROWS THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 4 - Erro: Múltiplas linhas.');
 WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('Bloco 4 - Outro erro capturado.');
END;
/

-- Bloco 5
DECLARE
 V_MENSAGEM VARCHAR2(50) := 'NeoHorizon API Test Log';
BEGIN
 FOR I IN 1..5 LOOP
   PRC_REGISTRAR_CONSULTA(1, V_MENSAGEM || ' - Bloco ' || I);
 END LOOP;
 DBMS_OUTPUT.PUT_LINE('Bloco 5 (FOR) - Consultas injetadas via lote com variáveis.');
EXCEPTION 
 WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 5 - Falha na inserção.');
END;
/

-- Bloco 6
DECLARE 
 V_IDX NUMBER := 1;
 V_EMP VARCHAR2(100);
BEGIN
 LOOP
   SELECT EMPRESA INTO V_EMP FROM CLIENTES WHERE ID_CLIENTE = V_IDX;
   DBMS_OUTPUT.PUT_LINE('Bloco 6 (LOOP-EXIT) - Cliente: ' || V_EMP);
   V_IDX := V_IDX + 1;
   EXIT WHEN V_IDX > 3;
 END LOOP;
EXCEPTION 
 WHEN NO_DATA_FOUND THEN 
    DBMS_OUTPUT.PUT_LINE('Bloco 6 - ID não localizado.');
END;
/

-- =====================================================
-- 11. RELATÓRIOS SQL
-- =====================================================
SELECT C.EMPRESA, CA.ENDPOINT, CA.DATA_CONSULTA
FROM CLIENTES C 
INNER JOIN CONSULTAS_API CA ON C.ID_CLIENTE = CA.ID_CLIENTE;

SELECT D.NOME AS DETRITO, O.ALTITUDE, O.VELOCIDADE
FROM DETRITOS D 
INNER JOIN ORBITAS O ON D.ID_DETRITO = O.ID_DETRITO;

SELECT D.NOME AS DETRITO, A.RISCO, A.STATUS AS STATUS_ALERTA
FROM DETRITOS D 
INNER JOIN ALERTAS A ON D.ID_DETRITO = A.ID_DETRITO;

SELECT S.NOME AS SATELITE, S.OPERADORA, C.PROBABILIDADE, C.DATA_PREVISTA
FROM SATELITES S 
INNER JOIN COLISOES_PREVISTAS C ON S.ID_SATELITE = C.ID_SATELITE;

SELECT D.NOME AS OBJETO_DETRITO, S.NOME AS SATELITE_ALVO, C.PROBABILIDADE || '%' AS CHANCE_COLISAO
FROM DETRITOS D
INNER JOIN COLISOES_PREVISTAS C ON D.ID_DETRITO = C.ID_DETRITO
INNER JOIN SATELITES S ON S.ID_SATELITE = C.ID_SATELITE;
