
-- =====================================================
-- ORBITALGUARD - GLOBAL SOLUTION 2026/1
-- ORACLE PL/SQL COMPLETE ACADEMIC TEMPLATE
-- =====================================================

-- 8 TABELAS, SEQUENCES, PROCEDURES, FUNCTIONS,
-- TRIGGERS, PACKAGE, CURSORES, BLOCOS ANONIMOS,
-- RELATORIOS E CARGA DE DADOS

CREATE TABLE CLIENTES(
 ID_CLIENTE NUMBER PRIMARY KEY,
 EMPRESA VARCHAR2(100) NOT NULL,
 EMAIL VARCHAR2(120) UNIQUE,
 API_KEY VARCHAR2(100) UNIQUE,
 PLANO VARCHAR2(20) CHECK (PLANO IN ('FREE','PRO','PREMIUM'))
);

CREATE TABLE DETRITOS(
 ID_DETRITO NUMBER PRIMARY KEY,
 NORAD_ID NUMBER UNIQUE NOT NULL,
 NOME VARCHAR2(100),
 TAMANHO NUMBER(10,2),
 MASSA NUMBER(10,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE ORBITAS(
 ID_ORBITA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ALTITUDE NUMBER(10,2),
 VELOCIDADE NUMBER(10,2),
 INCLINACAO NUMBER(10,2)
);

CREATE TABLE POSICOES(
 ID_POSICAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 LATITUDE NUMBER(10,6),
 LONGITUDE NUMBER(10,6),
 DATA_POSICAO DATE
);

CREATE TABLE ALERTAS(
 ID_ALERTA NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 RISCO NUMBER(5,2),
 STATUS VARCHAR2(20)
);

CREATE TABLE CONSULTAS_API(
 ID_CONSULTA NUMBER PRIMARY KEY,
 ID_CLIENTE NUMBER REFERENCES CLIENTES(ID_CLIENTE),
 ENDPOINT VARCHAR2(200),
 DATA_CONSULTA DATE
);

CREATE TABLE SATELITES(
 ID_SATELITE NUMBER PRIMARY KEY,
 NOME VARCHAR2(100),
 OPERADORA VARCHAR2(100),
 STATUS VARCHAR2(20)
);

CREATE TABLE COLISOES_PREVISTAS(
 ID_COLISAO NUMBER PRIMARY KEY,
 ID_DETRITO NUMBER REFERENCES DETRITOS(ID_DETRITO),
 ID_SATELITE NUMBER REFERENCES SATELITES(ID_SATELITE),
 PROBABILIDADE NUMBER(5,2),
 DATA_PREVISTA DATE
);

CREATE SEQUENCE SEQ_CLIENTES START WITH 1;
CREATE SEQUENCE SEQ_DETRITOS START WITH 1;
CREATE SEQUENCE SEQ_ORBITAS START WITH 1;
CREATE SEQUENCE SEQ_POSICOES START WITH 1;
CREATE SEQUENCE SEQ_ALERTAS START WITH 1;
CREATE SEQUENCE SEQ_CONSULTAS START WITH 1;
CREATE SEQUENCE SEQ_SATELITES START WITH 1;
CREATE SEQUENCE SEQ_COLISOES START WITH 1;

-- CARGA DE DADOS (90 REGISTROS)
BEGIN
 FOR I IN 1..10 LOOP
   INSERT INTO CLIENTES VALUES(I,'EMPRESA'||I,'EMAIL'||I||'@TESTE.COM','KEY'||I,
   CASE WHEN MOD(I,3)=0 THEN 'PREMIUM' WHEN MOD(I,2)=0 THEN 'PRO' ELSE 'FREE' END);
 END LOOP;

 FOR I IN 1..30 LOOP
   INSERT INTO DETRITOS VALUES(I,10000+I,'DETRITO'||I,I/2,I*5,'ATIVO');
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO ORBITAS VALUES(I,I,500+I,7.5,98);
 END LOOP;

 FOR I IN 1..20 LOOP
   INSERT INTO POSICOES VALUES(I,MOD(I,10)+1,-20+I,-40+I,SYSDATE-I);
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO ALERTAS VALUES(I,MOD(I,10)+1,50+I,'ATIVO');
 END LOOP;

 FOR I IN 1..10 LOOP
   INSERT INTO SATELITES VALUES(I,'SAT'||I,'OPERADORA'||I,'ATIVO');
 END LOOP;
 COMMIT;
END;
/

CREATE OR REPLACE FUNCTION FN_TOTAL_ALERTAS RETURN NUMBER IS
 V NUMBER;
BEGIN
 SELECT COUNT(*) INTO V FROM ALERTAS;
 RETURN V;
END;
/

CREATE OR REPLACE FUNCTION FN_CLIENTE_PREMIUM(P_ID NUMBER) RETURN VARCHAR2 IS
 V VARCHAR2(20);
BEGIN
 SELECT PLANO INTO V FROM CLIENTES WHERE ID_CLIENTE=P_ID;
 IF V='PREMIUM' THEN RETURN 'SIM'; ELSE RETURN 'NAO'; END IF;
END;
/

CREATE OR REPLACE FUNCTION FN_CALCULAR_RISCO(P_PROB NUMBER) RETURN VARCHAR2 IS
BEGIN
 IF P_PROB < 30 THEN RETURN 'BAIXO';
 ELSIF P_PROB < 70 THEN RETURN 'MEDIO';
 ELSE RETURN 'ALTO';
 END IF;
END;
/

CREATE OR REPLACE PROCEDURE PRC_GERAR_ALERTA(P_DETRITO NUMBER,P_RISCO NUMBER) IS
BEGIN
 INSERT INTO ALERTAS VALUES(SEQ_ALERTAS.NEXTVAL,P_DETRITO,P_RISCO,'ATIVO');
END;
/

CREATE OR REPLACE PROCEDURE PRC_REGISTRAR_CONSULTA(P_CLIENTE NUMBER,P_ENDPOINT VARCHAR2) IS
BEGIN
 INSERT INTO CONSULTAS_API VALUES(SEQ_CONSULTAS.NEXTVAL,P_CLIENTE,P_ENDPOINT,SYSDATE);
END;
/

CREATE OR REPLACE PROCEDURE PRC_ATUALIZAR_ORBITA(P_ID NUMBER,P_ALT NUMBER) IS
BEGIN
 UPDATE ORBITAS SET ALTITUDE=P_ALT WHERE ID_DETRITO=P_ID;
END;
/

CREATE OR REPLACE TRIGGER TRG_LOG_CONSULTA
AFTER INSERT ON CONSULTAS_API
FOR EACH ROW
BEGIN
 DBMS_OUTPUT.PUT_LINE('CONSULTA REGISTRADA');
END;
/

CREATE OR REPLACE TRIGGER TRG_ALERTA_COLISAO
AFTER INSERT ON COLISOES_PREVISTAS
FOR EACH ROW
BEGIN
 IF :NEW.PROBABILIDADE > 70 THEN
   INSERT INTO ALERTAS VALUES(SEQ_ALERTAS.NEXTVAL,:NEW.ID_DETRITO,:NEW.PROBABILIDADE,'ATIVO');
 END IF;
END;
/

CREATE OR REPLACE TRIGGER TRG_STATUS_DETRITO
BEFORE UPDATE ON DETRITOS
FOR EACH ROW
BEGIN
 :NEW.STATUS := UPPER(:NEW.STATUS);
END;
/

CREATE OR REPLACE PACKAGE PKG_ORBITAL_GUARD AS
 FUNCTION TOTAL_ALERTAS RETURN NUMBER;
 PROCEDURE GERAR_ALERTA(P_DETRITO NUMBER,P_RISCO NUMBER);
END;
/
CREATE OR REPLACE PACKAGE BODY PKG_ORBITAL_GUARD AS
 FUNCTION TOTAL_ALERTAS RETURN NUMBER IS
 BEGIN
  RETURN FN_TOTAL_ALERTAS;
 END;
 PROCEDURE GERAR_ALERTA(P_DETRITO NUMBER,P_RISCO NUMBER) IS
 BEGIN
  PRC_GERAR_ALERTA(P_DETRITO,P_RISCO);
 END;
END;
/

-- 4 CURSORES
DECLARE
 CURSOR C1 IS SELECT * FROM DETRITOS WHERE TAMANHO>1;
 R C1%ROWTYPE;
BEGIN
 OPEN C1; FETCH C1 INTO R; CLOSE C1;
END;
/

DECLARE
 CURSOR C2 IS SELECT * FROM CLIENTES WHERE PLANO='PREMIUM';
BEGIN NULL; END;
/

DECLARE
 CURSOR C3 IS SELECT * FROM ALERTAS;
BEGIN NULL; END;
/

DECLARE
 CURSOR C4 IS SELECT * FROM SATELITES;
BEGIN NULL; END;
/

-- 6 BLOCOS ANONIMOS
DECLARE V NUMBER;
BEGIN
 SELECT COUNT(*) INTO V FROM DETRITOS;
 DBMS_OUTPUT.PUT_LINE(V);
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
DECLARE V VARCHAR2(20);
BEGIN
 SELECT STATUS INTO V FROM DETRITOS WHERE ID_DETRITO=1;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
DECLARE V NUMBER:=80;
BEGIN
 IF V>70 THEN DBMS_OUTPUT.PUT_LINE('ALTO'); END IF;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
DECLARE I NUMBER:=1;
BEGIN
 WHILE I<5 LOOP I:=I+1; END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
DECLARE
BEGIN
 FOR I IN 1..5 LOOP NULL; END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
DECLARE X NUMBER:=0;
BEGIN
 LOOP
  X:=X+1;
  EXIT WHEN X=5;
 END LOOP;
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- RELATORIOS
SELECT C.EMPRESA,CA.ENDPOINT
FROM CLIENTES C JOIN CONSULTAS_API CA ON C.ID_CLIENTE=CA.ID_CLIENTE;

SELECT D.NOME,O.ALTITUDE
FROM DETRITOS D JOIN ORBITAS O ON D.ID_DETRITO=O.ID_DETRITO;

SELECT D.NOME,A.RISCO
FROM DETRITOS D JOIN ALERTAS A ON D.ID_DETRITO=A.ID_DETRITO;

SELECT S.NOME,C.PROBABILIDADE
FROM SATELITES S JOIN COLISOES_PREVISTAS C ON S.ID_SATELITE=C.ID_SATELITE;

SELECT D.NOME,S.NOME,C.PROBABILIDADE
FROM DETRITOS D
JOIN COLISOES_PREVISTAS C ON D.ID_DETRITO=C.ID_DETRITO
JOIN SATELITES S ON S.ID_SATELITE=C.ID_SATELITE;
